Repository python-visualization/folium, pull requests merged in 2019-03, with the labels that each got.

#1035 add options to draw control
  folium/plugins/draw.py
Labels: ready

#1058 Geojson styling overhaul
  folium/features.py
  folium/plugins/time_slider_choropleth.py
Labels: review needed

#1099 Icon: warn for wrong color value
  folium/map.py
  tests/test_map.py
Labels: review needed

#1090 Explicit coordinate validation
  examples/Plugins.ipynb
  folium/__init__.py
  folium/features.py
  folium/folium.py
  folium/map.py
  folium/plugins/antpath.py
  folium/plugins/boat_marker.py
  folium/plugins/fast_marker_cluster.py
  folium/plugins/heat_map.py
  folium/plugins/marker_cluster.py
  folium/utilities.py
  folium/vector_layers.py
  tests/plugins/test_antpath.py
  tests/plugins/test_fast_marker_cluster.py
  tests/plugins/test_heat_map.py
  tests/plugins/test_marker_cluster.py
  tests/test_utilities.py
Labels: review needed

#1109 Adding `icon_create_function` argument to Fast Marker Cluster plugin
  folium/plugins/fast_marker_cluster.py
  tests/plugins/test_fast_marker_cluster.py
Labels: in discussion
