Repository python-visualization/folium, pull requests merged in 2019-05, with the labels that each got.

#1133 Fix broken prefer_canvas option
  folium/folium.py
  tests/test_folium.py
Labels: ready

#1141 binder needs it at the root directory
  environment.yml
Labels: MentoredSprintsPyCon2019

#1155 Fix geojson identifier
  folium/features.py
  tests/test_features.py
Labels: review needed

#1140 added simple example using flask
  docs/flask.rst
  docs/index.rst
  examples/flask_example.py
Labels: MentoredSprintsPyCon2019

#1144 added message when key_on not found in geojson
  folium/features.py
Labels: MentoredSprintsPyCon2019
